# Generated by Django 5.2.15 on 2026-06-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_gradingconfig_grade_a_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bananaanalysisreport',
            name='side_annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='debug/side/'),
        ),
        migrations.AddField(
            model_name='bananaanalysisreport',
            name='top_annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='debug/top/'),
        ),
    ]
